### ISSUE TITLE
Uncaught DOMException

### ISSUE THREAD

**Issue by FaribaMp** [farshaddavoudi/Blazor.PersianDatePicker#47]
Hi 
Thank you for your useful NuGet package.
But there is a problem, when I clear value in DatePicker, this error occurs:

datepicker.min.js:180 Uncaught DOMException: Failed to execute 'matches' on 'Element': '[object HTMLInputElement]' is not a valid selector.
    at Object.J.matches (https://localhost:5030/_content/Blazor.PersianDatePicker/datepicker.min.js:180:3394)
    at f.is (https://localhost:5030/_content/Blazor.PersianDatePicker/datepicker.min.js:180:8016)
    at HTMLBodyElement.t (https://localhost:5030/_content/Blazor.PersianDatePicker/datepicker.min.js:180:93182)
    at HTMLBodyElement.i.proxy (https://localhost:5030/_content/Blazor.PersianDatePicker/datepicker.min.js:180:19172)

Could you help me?

**Comment by farshaddavoudi** [comment]
You are right. This problem causes no harm but is very ugly and unpleasant. I'm going to work on it and will solve it soon. Thanks for your comment ;)

**Comment by navidyazdi** [comment]
Just wanted to mention that I have the same problem!

**Comment by farshaddavoudi** [comment]
This issue was closed and has been resolved in mentioned PR. Thanks for all the patience and promising comments.
