### ISSUE TITLE
Error when I Use PersianDatePicker in a Modal in a Razor Page

### ISSUE THREAD

**Issue by mehdikangarloo** [farshaddavoudi/Blazor.PersianDatePicker#60]
Hi When I Use PersianDatePicker in a Modal in a Razor page an error Raise with this  message in console:
datepicker.min.js:106 Uncaught TypeError: selectedObject.includes is not a function
    at HTMLDocument.<anonymous> (datepicker.min.js:106:34)
    at HTMLDocument.dispatch (jquery-3.1.1.min.js:3:10315)
    at q.handle (jquery-3.1.1.min.js:3:8342)

**Comment by mehdikangarloo** [comment]
there is a solution in Stackoverflow site but your code in github appears incomplete and i cant use it

**Comment by farshaddavoudi** [comment]
Hi Mehdi, thanks for sharing the issue here. Are you using the latest version of the library [3.0.2]?

**Comment by mehdikangarloo** [comment]
Yes i am using the last version

**Comment by EsmaeelAmarloo** [comment]
Hi .when i set  parameter Value to '1402/01/01' and then click on input, selected day in datepicker is today not '1402/01/01'

**Comment by farshaddavoudi** [comment]
Hi @EsmaeelAmarloo 
Let me check. By the way, I hoped you could create a new issue as this issue is not related to the original issue.

**Comment by mehdikangarloo** [comment]
سلام اقای داودی modal من در یک razor page از طریق یک بولین و ست کردن مقدار
اون به TRUEنمایش داده میشه نمونه کدم رو فردا از سر کار براتون میفرستم من از
JQUERY برای ارسال پیام و دریافت تاییدیه استفاده کردم

**Comment by hache87** [comment]
سلام آقاي کنگرلو
من هم مشکل شمارا دارم.  محبت ميفرمائيد کد خود را برامن نيز بفرستيد.
mohraz94@chmail.ir

**Comment by farshaddavoudi** [comment]
@hache87 
سلام، وقت بخیر
آقای کنگرلو برام کدی نفرستادن و فکر کنم منظورشون راه حل نبود،‌ کدی که مشکل داشتن رو گفتن. حالا شما اگه علاقه دارید یه پروژه خیلی خلاصه و کوچیک که این مشکل توش وجود داشته باشه برای من بفرستید تا بررسیش کنم.

f.davoudi.r@outlook.com

**Comment by farshaddavoudi** [comment]
@hache87 

Hi, the package has been updated to v3.3 to cover your case. Updating it should fix your issue.

**Comment by hache87** [comment]
Thank you for your attention. Its solved the problem

**Comment by rezapaydar** [comment]
من هم این مشکل رو دارم و داخل مدال این رو برام نمایش نمیده حتی وقتی داخل مدال فراخوانیش میکنم هم نمایشش نمیده
